# Generated by Django 5.0.6 on 2024-07-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='db image')),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
